Add build tests for different ROS versions
ethz-asl/versavis pull request #24
Opened 2021-04-03 09:09 UTC by Jaeyoung-Lim

**Problem Description**
This commit adds a simple build test for the following ROS versions
- ROS Melodic
- ROS Noetic

**Additional Context**
- The package doesn't seem to work with ROS Noetic yet from https://github.com/ethz-asl/versavis/issues/21, but the catkin package still builds.

2021-04-03 09:11 UTC, Jaeyoung-Lim commented
The CI runs on my fork, but not here: https://github.com/Jaeyoung-Lim/versavis/pull/1 @floriantschopp Any idea why?

2021-04-06 07:01 UTC, floriantschopp requested changes
@Jaeyoung-Lim Thanks for adding this. I am new to GitHub releases, so not much experience there. Since VersaVIS depends on a lot more than just a successful build of the ROS packages, adding such tests was quite low priority. But it also can't hurt :-)

2021-04-06 07:01 UTC, floriantschopp commented on .github/workflows/build_test.yml
> +          - {rosdistro: 'noetic', container: 'px4io/px4-dev-ros-noetic:2020-08-20'}
could we also use a standard repo here instead px4io?

2021-04-06 07:01 UTC, floriantschopp commented on .github/workflows/build_test.yml
> +    - '*'
Are there also nightly tests?

2021-04-06 07:05 UTC, Jaeyoung-Lim commented on .github/workflows/build_test.yml
> +    - '*'
Yes!

2021-04-06 07:16 UTC, floriantschopp commented on .github/workflows/build_test.yml
> +    - '*'
I think we should add this, then I am fine for trying that change...

2021-04-06 07:25 UTC, Jaeyoung-Lim commented on .github/workflows/build_test.yml
> +    - '*'
Done! I have configured it to run 18:00 UTC everyday

2021-04-06 07:41 UTC, Jaeyoung-Lim commented
@floriantschopp Can we enable github actions for this repo? Then I can also add build status badges to the readme

2021-04-06 07:43 UTC, Jaeyoung-Lim commented on .github/workflows/build_test.yml
> +          - {rosdistro: 'noetic', container: 'px4io/px4-dev-ros-noetic:2020-08-20'}
Yeap, I think that makes more sense

2021-04-06 11:01 UTC, Jaeyoung-Lim commented on .github/workflows/build_test.yml
> +          - {rosdistro: 'noetic', container: 'px4io/px4-dev-ros-noetic:2020-08-20'}
Done!

2021-04-06 11:58 UTC, floriantschopp approved these changes
lgtm, thanks!!

2021-04-06 11:58 UTC, merged